##!/usr/bin/env bash
#
# 64px folders
#
./replace_folder_file.sh ../scalable/places/akonadi-phone-home.svg
./replace_folder_file.sh ../scalable/places/application-x-gnome-saved-search.svg
./replace_folder_file.sh ../scalable/places/bookmark-missing.svg
./replace_folder_file.sh ../scalable/places/certificate-server.svg
./replace_folder_file.sh ../scalable/places/default-bookmark-missing.svg
./replace_folder_file.sh ../scalable/places/default-cut.svg
./replace_folder_file.sh ../scalable/places/default-fileopen.svg
./replace_folder_file.sh ../scalable/places/default-folder.svg
./replace_folder_file.sh ../scalable/places/default-folder-activities.svg
./replace_folder_file.sh ../scalable/places/default-folder-bookmark.svg
./replace_folder_file.sh ../scalable/places/default-folder-build.svg
./replace_folder_file.sh ../scalable/places/default-folder-camera.svg
./replace_folder_file.sh ../scalable/places/default-folder-cloud.svg
./replace_folder_file.sh ../scalable/places/default-folder-decrypted.svg
./replace_folder_file.sh ../scalable/places/default-folder-documents.svg
./replace_folder_file.sh ../scalable/places/default-folder-download.svg
./replace_folder_file.sh ../scalable/places/default-folder-games.svg
./replace_folder_file.sh ../scalable/places/default-folder-gdrive.svg
./replace_folder_file.sh ../scalable/places/default-folder-git.svg
./replace_folder_file.sh ../scalable/places/default-folder-github.svg
./replace_folder_file.sh ../scalable/places/default-folder-gradle.svg
./replace_folder_file.sh ../scalable/places/default-folder-important.svg
./replace_folder_file.sh ../scalable/places/default-folder-locked.svg
./replace_folder_file.sh ../scalable/places/default-folder-mail.svg
./replace_folder_file.sh ../scalable/places/default-folder-move.svg
./replace_folder_file.sh ../scalable/places/default-folder-music.svg
./replace_folder_file.sh ../scalable/places/default-folder-open.svg
./replace_folder_file.sh ../scalable/places/default-folder-pictures.svg
./replace_folder_file.sh ../scalable/places/default-folder-print.svg
./replace_folder_file.sh ../scalable/places/default-folder-publicshare.svg
./replace_folder_file.sh ../scalable/places/default-folder-recent.svg
./replace_folder_file.sh ../scalable/places/default-folder-root.svg
./replace_folder_file.sh ../scalable/places/default-folder-saved-search.svg
./replace_folder_file.sh ../scalable/places/default-folder-script.svg
./replace_folder_file.sh ../scalable/places/default-folder-stack.svg
./replace_folder_file.sh ../scalable/places/default-folder-system.svg
./replace_folder_file.sh ../scalable/places/default-folder-tar.svg
./replace_folder_file.sh ../scalable/places/default-folder-templates.svg
./replace_folder_file.sh ../scalable/places/default-folder-unity.svg
./replace_folder_file.sh ../scalable/places/default-folder-video.svg
./replace_folder_file.sh ../scalable/places/default-network.svg
./replace_folder_file.sh ../scalable/places/default-network-server.svg
./replace_folder_file.sh ../scalable/places/default-user-desktop.svg
./replace_folder_file.sh ../scalable/places/default-user-home.svg
./replace_folder_file.sh ../scalable/places/desktop.svg
./replace_folder_file.sh ../scalable/places/document-open-recent.svg
./replace_folder_file.sh ../scalable/places/favorites.svg
./replace_folder_file.sh ../scalable/places/fileopen.svg
./replace_folder_file.sh ../scalable/places/folder.svg
./replace_folder_file.sh ../scalable/places/folder-activities.svg
./replace_folder_file.sh ../scalable/places/folder-bookmark.svg
./replace_folder_file.sh ../scalable/places/folder-bookmarks.svg
./replace_folder_file.sh ../scalable/places/folder_color_default.svg
./replace_folder_file.sh ../scalable/places/folder_color_default_desktop.svg
./replace_folder_file.sh ../scalable/places/folder_color_default_documents.svg
./replace_folder_file.sh ../scalable/places/folder_color_default_downloads.svg
./replace_folder_file.sh ../scalable/places/folder_color_default_music.svg
./replace_folder_file.sh ../scalable/places/folder_color_default_pictures.svg
./replace_folder_file.sh ../scalable/places/folder_color_default_public.svg
./replace_folder_file.sh ../scalable/places/folder_color_default_templates.svg
./replace_folder_file.sh ../scalable/places/folder_color_default_videos.svg
./replace_folder_file.sh ../scalable/places/folder-copy.svg
./replace_folder_file.sh ../scalable/places/folder-decrypted.svg
./replace_folder_file.sh ../scalable/places/folder-desktop.svg
./replace_folder_file.sh ../scalable/places/folder-development.svg
./replace_folder_file.sh ../scalable/places/folder-documents.svg
./replace_folder_file.sh ../scalable/places/folder-download.svg
./replace_folder_file.sh ../scalable/places/folder_download.svg
./replace_folder_file.sh ../scalable/places/folder-downloads.svg
./replace_folder_file.sh ../scalable/places/folder_downloads.svg
./replace_folder_file.sh ../scalable/places/folder-drag-accept.svg
./replace_folder_file.sh ../scalable/places/folder-dropbox.svg
./replace_folder_file.sh ../scalable/places/folder-encrypted.svg
./replace_folder_file.sh ../scalable/places/folder-favorites.svg
./replace_folder_file.sh ../scalable/places/folder-games.svg
./replace_folder_file.sh ../scalable/places/folder-gdrive.svg
./replace_folder_file.sh ../scalable/places/folder-green.svg
./replace_folder_file.sh ../scalable/places/folder-grey.svg
./replace_folder_file.sh ../scalable/places/folder-home.svg
./replace_folder_file.sh ../scalable/places/folder_home.svg
./replace_folder_file.sh ../scalable/places/folder-html.svg
./replace_folder_file.sh ../scalable/places/folder_html.svg
./replace_folder_file.sh ../scalable/places/folder-image.svg
./replace_folder_file.sh ../scalable/places/folder-image-people.svg
./replace_folder_file.sh ../scalable/places/folder-images.svg
./replace_folder_file.sh ../scalable/places/folder_images.svg
./replace_folder_file.sh ../scalable/places/folder-important.svg
./replace_folder_file.sh ../scalable/places/folder-locked.svg
./replace_folder_file.sh ../scalable/places/folder-mail.svg
./replace_folder_file.sh ../scalable/places/folder-move.svg
./replace_folder_file.sh ../scalable/places/folder-music.svg
./replace_folder_file.sh ../scalable/places/folder-network.svg
./replace_folder_file.sh ../scalable/places/folder-onedrive.svg
./replace_folder_file.sh ../scalable/places/folder-open.svg
./replace_folder_file.sh ../scalable/places/folder_open.svg
./replace_folder_file.sh ../scalable/places/folder-owncloud.svg
./replace_folder_file.sh ../scalable/places/folder-photo.svg
./replace_folder_file.sh ../scalable/places/folder-photos.svg
./replace_folder_file.sh ../scalable/places/folder-picture.svg
./replace_folder_file.sh ../scalable/places/folder-pictures.svg
./replace_folder_file.sh ../scalable/places/folder_pictures.svg
./replace_folder_file.sh ../scalable/places/folder-print.svg
./replace_folder_file.sh ../scalable/places/folder-private.svg
./replace_folder_file.sh ../scalable/places/folder-public.svg
./replace_folder_file.sh ../scalable/places/folder-publicshare.svg
./replace_folder_file.sh ../scalable/places/folder-recent.svg
./replace_folder_file.sh ../scalable/places/folder-remote.svg
./replace_folder_file.sh ../scalable/places/folder-remote-ftp.svg
./replace_folder_file.sh ../scalable/places/folder-remote-nfs.svg
./replace_folder_file.sh ../scalable/places/folder-remote-smb.svg
./replace_folder_file.sh ../scalable/places/folder-remote-ssh.svg
./replace_folder_file.sh ../scalable/places/folder-root.svg
./replace_folder_file.sh ../scalable/places/folder-saved-search.svg
./replace_folder_file.sh ../scalable/places/folder-saved-search-alt.svg
./replace_folder_file.sh ../scalable/places/folder-script.svg
./replace_folder_file.sh ../scalable/places/folders-documents.svg
./replace_folder_file.sh ../scalable/places/folders-downloads.svg
./replace_folder_file.sh ../scalable/places/folders-music.svg
./replace_folder_file.sh ../scalable/places/folder-sound.svg
./replace_folder_file.sh ../scalable/places/folders-publicshare.svg
./replace_folder_file.sh ../scalable/places/folders-videos.svg
./replace_folder_file.sh ../scalable/places/folder-system.svg
./replace_folder_file.sh ../scalable/places/folder-tar.svg
./replace_folder_file.sh ../scalable/places/folder-temp.svg
./replace_folder_file.sh ../scalable/places/folder-templates.svg
./replace_folder_file.sh ../scalable/places/folder-text.svg
./replace_folder_file.sh ../scalable/places/folder-txt.svg
./replace_folder_file.sh ../scalable/places/folder-unlocked.svg
./replace_folder_file.sh ../scalable/places/folder-video.svg
./replace_folder_file.sh ../scalable/places/folder-videocamera.svg
./replace_folder_file.sh ../scalable/places/folder-videos.svg
./replace_folder_file.sh ../scalable/places/gnome-dev-network.svg
./replace_folder_file.sh ../scalable/places/gnome-folder.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-blockdev.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-bookmark.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-bookmark-missing.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-dav.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-desktop.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-dev.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-directory.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-directory-accept.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-directory-visiting.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-ftp.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-home.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-network.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-nfs.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-server.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-share.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-smb.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-ssh.svg
./replace_folder_file.sh ../scalable/places/gnome-fs-web.svg
./replace_folder_file.sh ../scalable/places/gnome-home.svg
./replace_folder_file.sh ../scalable/places/gnome-mime-x-directory-nfs-server.svg
./replace_folder_file.sh ../scalable/places/gnome-mime-x-directory-smb-server.svg
./replace_folder_file.sh ../scalable/places/gnome-mime-x-directory-smb-share.svg
./replace_folder_file.sh ../scalable/places/gnome-mime-x-directory-smb-workgroup.svg
./replace_folder_file.sh ../scalable/places/go-home.svg
./replace_folder_file.sh ../scalable/places/gohome.svg
./replace_folder_file.sh ../scalable/places/go-home-large.svg
./replace_folder_file.sh ../scalable/places/gtg-home.svg
./replace_folder_file.sh ../scalable/places/gtk-directory.svg
./replace_folder_file.sh ../scalable/places/gtk-home.svg
./replace_folder_file.sh ../scalable/places/gtk-network.svg
./replace_folder_file.sh ../scalable/places/kfm_home.svg
./replace_folder_file.sh ../scalable/places/knetattach.svg
./replace_folder_file.sh ../scalable/places/library-music.svg
./replace_folder_file.sh ../scalable/places/neat.svg
./replace_folder_file.sh ../scalable/places/network.svg
./replace_folder_file.sh ../scalable/places/network_fs.svg
./replace_folder_file.sh ../scalable/places/network_local.svg
./replace_folder_file.sh ../scalable/places/network-server.svg
./replace_folder_file.sh ../scalable/places/network-workgroup.svg
./replace_folder_file.sh ../scalable/places/nfs.svg
./replace_folder_file.sh ../scalable/places/redhat-home.svg
./replace_folder_file.sh ../scalable/places/redhat-network-server.svg
./replace_folder_file.sh ../scalable/places/redhat-system-group.svg
./replace_folder_file.sh ../scalable/places/repository.svg
./replace_folder_file.sh ../scalable/places/samba.svg
./replace_folder_file.sh ../scalable/places/server.svg
./replace_folder_file.sh ../scalable/places/stock_bookmark.svg
./replace_folder_file.sh ../scalable/places/stock_delete-bookmark.svg
./replace_folder_file.sh ../scalable/places/stock_folder.svg
./replace_folder_file.sh ../scalable/places/stock_folder-copy.svg
./replace_folder_file.sh ../scalable/places/stock_folder-move.svg
./replace_folder_file.sh ../scalable/places/stock_home.svg
./replace_folder_file.sh ../scalable/places/stock_music-library.svg
./replace_folder_file.sh ../scalable/places/stock_open.svg
./replace_folder_file.sh ../scalable/places/stock_shared-by-me.svg
./replace_folder_file.sh ../scalable/places/stock_shared-to-me.svg
./replace_folder_file.sh ../scalable/places/user-bookmarks.svg
./replace_folder_file.sh ../scalable/places/user-desktop.svg
./replace_folder_file.sh ../scalable/places/user-home.svg
./replace_folder_file.sh ../scalable/places/user-images.svg
./replace_folder_file.sh ../scalable/places/user-pictures.svg
./replace_folder_file.sh ../scalable/places/user-share.svg
